- name: create virtualenv
  command: virtualenv {{ virtualenv_path }} creates={{ virtualenv_path }}

- name: install gunicorn
  pip: name=gunicorn virtualenv={{ virtualenv_path }}

- name: install gdal
  environment:
    CPLUS_INCLUDE_PATH: /usr/include/gdal
    C_INCLUDE_PATH: /usr/include/gdal
  pip: name=gdal version="1.10" virtualenv={{ virtualenv_path }}

- name: install psycopg2
  pip: name=psycopg2 virtualenv={{ virtualenv_path }}